Add splunk app for elements security events integration with splunk
SDS-2023/splunk-elements-integration pull request #2
Opened 2023-07-23 21:56 UTC by dlisiewicz

2023-07-24 16:18 UTC, brusju requested changes
Nice work, just few requests / open questions from my side.

2023-07-24 16:18 UTC, brusju commented on wsapp.png
I am not sure if We are legally allowed to use WithSecure logo here and for wsapp_dark.png. Maybe It would be safer to use some neutral placeholder here, what Do You think @wozprzemek  ?

2023-07-24 16:18 UTC, brusju commented on wsapp_connector.py
> +        token_url = 'https://api.connect-stg.fsapi.com/as/token.oauth2'
Here we expose elements staging api url. Not sure if this is an issue but maybe would be safer to move this to the config just like base url.

2023-07-24 16:18 UTC, brusju commented on wsappclone.json
> +            "default": "https://api.connect-stg.fsapi.com/",
Same here, not sure if this url should be present here.

2023-07-24 21:55 UTC, wozprzemek reviewed
Please review and address the comments

2023-07-24 21:55 UTC, wozprzemek commented on wsapp.png
Right, might be a good idea to make sure it can be used here. A placeholder for now would be ok

2023-07-24 21:55 UTC, wozprzemek commented on wsapp_connector.py
> +        token_url = 'https://api.connect-stg.fsapi.com/as/token.oauth2'
Agreed

2023-07-25 20:36 UTC, brusju approved these changes

2023-07-25 21:10 UTC, wozprzemek approved these changes

2023-07-25 21:14 UTC, merged